configs:
    use: 'home'
    home:
      public_ip: '192.168.0.111'
      connection: 'en0: Wi-Fi (AirPort)'
    office:
      public_ip: '192.168.0.121'
      connection: 'en4: Thunderbolt Ethernet'
domain_name: 'app.example.com'
hostname: 'php-box'
ports:
    ssl:
      guest: '22'
      host: '50201'
    apache:
      guest: '80'
      host: '50202'
    mysql:
      guest: '3306'
      host: '50203'
    apache_ssl:
      guest: '443'
      host: '50204'
